### ISSUE TITLE
js8tnc.py frame decoding errors 

### ISSUE THREAD

**Issue by W5DMH** [punk-kaos/JS8TNC#1]
Hello, 
I am using a Raspberry Pi 4  and  YAAC as the KISS TNC over TCP Client and I am also running a Serial TNC port on YAAC as well, the callsign is W5DMH on both JS8Call and YAAC. 

I send "??" over the air to the above radio & callsign (W5DMH) from another radio and callsign (W5DMH-9) and I get the following frame decode errors (below is an image of the raw text as well) : 

 JS8Call TNC V0.2
Waiting for JS8 to connect...
JS8 Connected ('127.0.0.1', 55567)
TNC started on port 8001
Waiting for TNC client to connect...
TNC Client connected from:  ('127.0.0.1', 44246)
KISS loop
TNC:
Error decoding frame.
KISS loop
@@`j@`d@c:W5DMH-9  :ack7
Error decoding frame.
KISS loop
@@`j@`d@c:W5DMH-9  :ack7
Error decoding frame.
KISS loop
@@`j@`d@c:W5DMH-9  :ack7
Error decoding frame.
KISS loop

![image](https://user-images.githubusercontent.com/34745389/208914764-5cc1c1dc-449b-426c-adf1-f0aa7af72ec9.png)

**Comment by punk-kaos** [comment]
Took me a while to get around to fixing it... But everything works with latest JS8 API now. Rewrote a bunch of the handlers and AUGHT to be a bit more robust now.
